require("mfathonin.plugins.nvim-tree")
require("mfathonin.plugins.telescope")
require("mfathonin.plugins.treesitter")
require("mfathonin.plugins.web-devicons")
require("mfathonin.plugins.lsp-config")
require("mfathonin.plugins.toggleterm")
